In [5]:
import pandas as pd
import numpy as np

In [6]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([array1, array1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([array1, array1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
# concatenar series

serie1 = pd.Series([1,2,3], index=['a','b','c'])
serie1

a    1
b    2
c    3
dtype: int64

In [11]:
serie2 = pd.Series([4,5,6], index=['d','e','f'])
serie2

d    4
e    5
f    6
dtype: int64

In [14]:
pd.concat([serie1, serie2], keys=['serie1', 'serie2'])

serie1  a    1
        b    2
        c    3
serie2  d    4
        e    5
        f    6
dtype: int64

In [16]:
dataframe1 = pd.DataFrame(np.random.rand(3,3), columns = ['a', 'b','c'])
dataframe1

a         b         c
0  0.241185  0.941403  0.418747
1  0.033389  0.567288  0.996344
2  0.985144  0.005268  0.982586

In [17]:
dataframe2 = pd.DataFrame(np.random.rand(2,3), columns = ['a', 'b','c'])
dataframe2

a         b         c
0  0.932857  0.035667  0.207537
1  0.113660  0.353025  0.177371

In [18]:
dataframe3 = pd.concat([dataframe1, dataframe2])
dataframe3

a         b         c
0  0.241185  0.941403  0.418747
1  0.033389  0.567288  0.996344
2  0.985144  0.005268  0.982586
0  0.932857  0.035667  0.207537
1  0.113660  0.353025  0.177371

In [19]:
dataframe3 = pd.concat([dataframe1, dataframe2], ignore_index = True)
dataframe3

a         b         c
0  0.241185  0.941403  0.418747
1  0.033389  0.567288  0.996344
2  0.985144  0.005268  0.982586
3  0.932857  0.035667  0.207537
4  0.113660  0.353025  0.177371