In [1]:
# creando arrays

import numpy as np

np.zeros(4)

array([0., 0., 0., 0.])

In [2]:
np.ones(4)

array([1., 1., 1., 1.])

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [6]:
lista1 = [1,2,3,4]
array1 = np.array(lista1)

In [7]:
array1

array([1, 2, 3, 4])

In [8]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)
lista_doble

([1, 2, 3, 4], [5, 6, 7, 8])

In [9]:
array_doble = np.array(lista_doble)

In [10]:
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
array_doble.shape # forma de la matriz, en este caso dos filas 4 columnas

(2, 4)

In [13]:
array_doble.dtype 

dtype('int32')

In [24]:
# operaciones con arrays

array1 = np.array([1,2,3,4])

array1 ** 3

array1 + 4

array1 = array1 ** 3
array1

array([ 1,  8, 27, 64], dtype=int32)

In [28]:
lista1 = [1,2,3,4]
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)
lista_doble
array_doble = np.array(lista_doble)
array_doble + 5 
array_doble / 5

array([[0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6]])

In [29]:
# indexacion 
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
array_copia = array.copy()
array_copia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
array_copia[0:3] = 20
array_copia

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# array dos dimensiones

array2 = np.array(([1,2,3], [4,5,6], [7,8,9]))
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array2[0][2]

3

In [40]:
# matrices traspuestas

array = np.arange(15).reshape((3,5)) # reshape => forma en esta caso 3 filas 5 columnas 
array
array_tras = array.T
array_tras

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
# entraada y salida con arrays

array1 = np.arange(6)
array2 = np.arange(8)


In [42]:
np.save('array1', array1) #guardamos un array para usarlo despues

In [52]:
np.load('array1.npy')

# guardar dos arrays a la vez
np.savez('arrays', x=array1, y=array2) 
array_recup = np.load('arrays.npz')
array_recup['x']
array_recup['y']

array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
# guardar array en fichero de texto
np.savetxt('mificheroarray.txt', array2, delimiter = ',')
np.loadtxt('mificheroarray.txt', delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [72]:
# fn con arrays


np.sqrt(array1) # raiz cuadradada

np.random.rand(5)

lista1 = [0,1,2,3,4]
lista = [5,6,7,8,9]
array1 = np.array(lista1)
array2 = np.array(lista)
array2

np.add(array1, array2)

array([ 5,  7,  9, 11, 13])

In [75]:
np.maximum(array1, array2)

ValueError: invalid number of arguments

In [78]:
# ejercicio 

"""
crear fn pares que devuelva un array de numeros pares entre dos valores pasados como parametros a la fn (inicio y fin)
Utilizar la fn "pares" con los numeros 1 y 30
Utilizar la fn "pares" con los valores 2 y 40
"""

def pares(inicio, fin):
    if(inicio % 2 == 0):
        array = np.arange(inicio, fin, 2)
    else:
        inicio += 1
        array = np.arange(inicio, fin,2)
    return array

pares(2,40)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])